In [1]:
import numpy as np

In [2]:
#numpy arrays and it is two type - vector (one dimentional) and matrix (two dimentional); here dimention mean row and column

In [3]:
my_list = [1, 0 , - 1]
print(my_list)

[1, 0, -1]


In [4]:
my_array = np.array(my_list)
print(my_array)

[ 1  0 -1]


In [7]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8 ,9], [4,5,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [4, 5, 9]]


In [8]:
matrix_one = np.array(my_matrix)
print(matrix_one)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 9]]


In [9]:
print(type(matrix_one))

<class 'numpy.ndarray'>


In [11]:
my_tuple = (-1, 0, 1)
print(my_tuple)

(-1, 0, 1)


In [12]:
my_array1 = np.array(my_tuple)
print(my_array1)

[-1  0  1]


In [13]:
print(type(my_array1))

<class 'numpy.ndarray'>


In [15]:
#arange function of Numpy; NOTE: ARANGE is consist with one R not ARRANGE 
np.arange(100) #it will evenly arange between 0 to 99 excluding 100 like range() in core python

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
#to see the documentation of the function we can type help(np.arrange), or ?np.arange or shift+tab

In [17]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [18]:
?np.arange

In [ ]:
np.arange #shift + tab to see documentation

In [19]:
#now using steps and guides in arange function
np.arange(3,10,2) #here 3 is the starting point, 10 is the stop point (excluding 10), and 2 is the gap between two digits

array([3, 5, 7, 9])

In [20]:
np.arange(100, 1000, 10)

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220,
       230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350,
       360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480,
       490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610,
       620, 630, 640, 650, 660, 670, 680, 690, 700, 710, 720, 730, 740,
       750, 760, 770, 780, 790, 800, 810, 820, 830, 840, 850, 860, 870,
       880, 890, 900, 910, 920, 930, 940, 950, 960, 970, 980, 990])

In [21]:
#we can aslo define data type in arange function
np.arange(3,15,3, dtype=float) #here dtype is to define datatype after defining the start, end, and step or gap

array([ 3.,  6.,  9., 12.])

In [24]:
#linspace is to distribute between two numbers evenly
np.linspace(1,3,10) #here 1 is the starting point, 3 is the stop point and 10 is the number of output

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [26]:
#retstep is to deetermine the output of gap between two numbers
np.linspace(1, 2, 100, retstep= True)

(array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
        1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
        1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
        1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
        1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
        1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
        1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
        1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
        1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
        1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
        1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
        1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
        1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
        1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
        1.70707071, 1.71717172, 1.72727273, 1.73